source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlienKit_Example', :exclusive => true do
  pod 'AlienKit', :path => '../'
end

target 'AlienKit_Tests', :exclusive => true do
  pod 'AlienKit', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.2.0'
end
