source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlienKit_Example', :exclusive => true do
  pod 'AlienKit', :path => '../'
end

target 'AlienKit_Tests', :exclusive => true do
  # Hack until changes in master branch gets tagged

  pod 'AlienKit', :path => '../'

end
